on: [push, pull_request]

name: Continuous Integration

jobs:
  check:
    name: Cargo check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Testsuite with all features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  cortex_m_build:
    name: No-std compat (x-build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: thumbv7m-none-eabi
      - name: Check default (zero) features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target thumbv7m-none-eabi
      - name: Check tracing feature
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target thumbv7m-none-eabi --features tracing
      - name: Check postcard-codec feature
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target thumbv7m-none-eabi --features postcard-codec
      - name: Check every no-std feature
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --target thumbv7m-none-eabi --features tracing,postcard-codec

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features -- -D warnings

  features:
    name: Features Powerset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install cargo-hack
        run: cargo install cargo-hack
      - name: Run checks
        run: cargo hack check --feature-powerset --no-dev-deps
